# This file is a template, and might need editing before it works on your project.
# Official docker image.

before_script:
- docker info
- git submodule update --init --recursive

build:
  stage: build
  tags:
    - Resin
  script:
  - pwd
  - sleep 5
  - source layers/poke/oe-build-env
  - bitbake resin-image