# This file is a template, and might need editing before it works on your project.
# Official docker image.

before_script:
  #- 'sudo apt-get update && apt-get install -y sudo gawk wget git-core diffstat unzip texinfo gcc-multilib \
#build-essential chrpath socat libsdl1.2-dev xterm lzop'

  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - docker info
  - git submodule update --init --recursive

build:
  stage: build
  tags:
    - Resin
  script:
  - source layers/poky/oe-init-build-env
  - bitbake resin-image
  artifacts:
    name:
      ResinOS
    paths:
      - build/tmp/deploy/images/chip/images
  cache:
    paths:
    - build/