# This file is a template, and might need editing before it works on your project.
# Official docker image.

before_script:
  # Cleanup Docker
  - docker ps -a -q && ps -ef | grep dockerd | grep -v grep | awk '{print $2}' | sudo xargs kill
  - sleep 2
  - sudo rm -rf /var/lib/docker/devicemapper/
  - sudo dockerd --storage-driver=devicemapper &
  - sleep 10
  - docker rm $(docker ps -a -q) || echo skip
  - docker rmi -f $(docker images -q) || echo skip
  #- 'sudo apt-get update && apt-get install -y sudo gawk wget git-core diffstat unzip texinfo gcc-multilib \
  #build-essential chrpath socat libsdl1.2-dev xterm lzop'

  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent (inside the build environment)
  # - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  # - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # - mkdir -p ~/.ssh
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - docker info
  - git submodule update --init --recursive

build:
  stage: build
  tags:
    - Resin
  script:
  #- source layers/poky/oe-init-build-env
  #- bitbake resin-image
  #- cd -
  - sed -i 's/TARGET_TAG ?= "v2.6.2"/TARGET_TAG ?= "v2.3.0"/g' layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
  - rm -rf /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/deploy/images/chip/ubinize_resin-ubi.cfg
  - rm -rf /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/deploy/images/chip/data.ubifs
  - rm -rf /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/deploy/images/chip/boot.ubifs
  - rm -rf /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/deploy/images/chip/conf.ubifs
  - rm -rf /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/deploy/images/chip/resin-image-chip*
  - source layers/poky/oe-init-build-env
  - env > /tmp/getenv
  - mv tmp tmp.old
  - mkdir -p /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}
  - ln -s /dev/shm/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME} tmp
  #- bitbake -f -c compile docker-resin-supervisor-disk
  - bitbake resin-image
  - echo Copying image files for flashing with CHIP-tools and http://flash.getchip.com
  - ls -laR tmp/deploy/images/chip/images/
  - cp -av tmp/deploy/images/chip/images ../images
  # Kill Docker
  - docker ps -a -q && ps -ef | grep dockerd | grep -v grep | awk '{print $2}' | sudo xargs kill
  artifacts:
    name:
      ResinOS
    paths:
      - ./images
  cache:
    paths:
    - build/
