# This file is a template, and might need editing before it works on your project.
# Official docker image.

before_script:
  # Cleanup Docker
  - docker ps -a -q || ps -ef | grep dockerd | grep -v grep | awk '{print $2}' | sudo xargs kill
  - sudo rm -rf /var/lib/docker/devicemapper/
  - sudo dockerd --storage-driver=devicemapper &
  - docker ps -a -q || docker rm -f $(docker ps -a -q)
  - docker images -q || docker rmi -f $(docker images -q)
  #- 'sudo apt-get update && apt-get install -y sudo gawk wget git-core diffstat unzip texinfo gcc-multilib \
  #build-essential chrpath socat libsdl1.2-dev xterm lzop'

  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - docker info
  - git submodule update --init --recursive

build:
  stage: build
  tags:
    - Resin
  script:
  - source layers/poky/oe-init-build-env
  - bitbake resin-image
  - cd -
  - sed -i 's/TARGET_TAG ?= "v2.6.2"/TARGET_TAG ?= "v2.3.0"/g' layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
  - rm -rf build/tmp/deploy/images/chip/ubinize_resin-ubi.cfg
  - rm -rf build/tmp/deploy/images/chip/data.ubifs
  - rm -rf build/tmp/deploy/images/chip/boot.ubifs
  - rm -rf build/tmp/deploy/images/chip/conf.ubifs
  - rm -rf build/tmp/deploy/images/chip/data_disk/
  - rm -rf build/tmp/deploy/images/chip/data_disk.img
  - rm -rf build/tmp/deploy/images/chip/resin-image-chip*
  - source layers/poky/oe-init-build-env
  - bitbake -f -c compile docker-resin-supervisor-disk
  - bitbake resin-image
  artifacts:
    name:
      ResinOS
    paths:
      - build/tmp/deploy/images/chip/images
  #cache:
  #  paths:
  #  - build/